# Build settings
plugins:
  - jekyll-postcss

include:
  - _pages

collections:
  work_items:
    output: true
    permalink: /:path/
    sort_by: order

#Site info
title: "Jesse Trippe &#124; Product and UX Designer"
description: "Website of Jesse Trippe—a Product and UX Designer working at Amazon in Seattle, WA."
author: "Jesse Trippe"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - package.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - netlify.toml
  - bin
  - .gitignore

# Use NODE_ENV=production to trigger purgecss
